version: '3.7'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
